// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttestationRequest {
    /// TEE enum. Specify the evidence type
    #[prost(string, tag = "1")]
    pub tee: ::prost::alloc::string::String,
    /// Base64 encoded evidence. The alphabet is URL_SAFE_NO_PAD.
    /// defined in <https://datatracker.ietf.org/doc/html/rfc4648#section-5>
    #[prost(string, tag = "2")]
    pub evidence: ::prost::alloc::string::String,
    /// Hash algorithm used to calculate runtime data. Currently can be "sha256",
    /// "sha384" or "sha512". If not specified, "sha384" will be selected.
    #[prost(string, tag = "7")]
    pub runtime_data_hash_algorithm: ::prost::alloc::string::String,
    /// Hash algorithm used to calculate init data. Currently can be "sha256",
    /// "sha384" or "sha512". If not specified, "sha384" will be selected.
    #[prost(string, tag = "8")]
    pub init_data_hash_algorithm: ::prost::alloc::string::String,
    /// List of IDs of the policy used to check evidence. If not provided,
    /// a "default" one will be used.
    #[prost(string, repeated, tag = "9")]
    pub policy_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Runtime Data used to check the binding relationship with report data in
    /// Evidence
    #[prost(oneof = "attestation_request::RuntimeData", tags = "3, 4")]
    pub runtime_data: ::core::option::Option<attestation_request::RuntimeData>,
    /// Init Data used to check the binding relationship with init data in
    /// Evidence
    #[prost(oneof = "attestation_request::InitData", tags = "5, 6")]
    pub init_data: ::core::option::Option<attestation_request::InitData>,
}
/// Nested message and enum types in `AttestationRequest`.
pub mod attestation_request {
    /// Runtime Data used to check the binding relationship with report data in
    /// Evidence
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum RuntimeData {
        /// Base64 encoded runtime data slice. The whole string will be base64
        /// decoded. The result one will then be accumulated into a digest which
        /// is used as the expected runtime data to check against the one inside
        /// evidence.
        ///
        /// The alphabet is URL_SAFE_NO_PAD.
        /// defined in <https://datatracker.ietf.org/doc/html/rfc4648#section-5>
        #[prost(string, tag = "3")]
        RawRuntimeData(::prost::alloc::string::String),
        /// Runtime data in a JSON map. CoCoAS will rearrange each layer of the
        /// data JSON object in dictionary order by key, then serialize and output
        /// it into a compact string, and perform hash calculation on the whole
        /// to check against the one inside evidence.
        ///
        /// After the verification, the structured runtime data field will be included
        /// inside the token claims.
        #[prost(string, tag = "4")]
        StructuredRuntimeData(::prost::alloc::string::String),
    }
    /// Init Data used to check the binding relationship with init data in
    /// Evidence
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum InitData {
        /// Base64 encoded init data slice. The whole string will be base64
        /// decoded. The result one will then be accumulated into a digest which
        /// is used as the expected init data to check against the one inside
        /// evidence.
        ///
        /// The alphabet is URL_SAFE_NO_PAD.
        /// defined in <https://datatracker.ietf.org/doc/html/rfc4648#section-5>
        #[prost(string, tag = "5")]
        RawInitData(::prost::alloc::string::String),
        /// Init data in a JSON map. CoCoAS will rearrange each layer of the
        /// data JSON object in dictionary order by key, then serialize and output
        /// it into a compact string, and perform hash calculation on the whole
        /// to check against the one inside evidence.
        ///
        /// After the verification, the structured init data field will be included
        /// inside the token claims.
        #[prost(string, tag = "6")]
        StructuredInitData(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttestationResponse {
    #[prost(string, tag = "1")]
    pub attestation_token: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPolicyRequest {
    #[prost(string, tag = "1")]
    pub policy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub policy: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetPolicyResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChallengeRequest {
    /// ChallengeRequest uses HashMap to pass variables like:
    /// tee, tee_params etc
    #[prost(map = "string, string", tag = "1")]
    pub inner: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChallengeResponse {
    #[prost(string, tag = "1")]
    pub attestation_challenge: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod attestation_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AttestationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AttestationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AttestationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AttestationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            AttestationServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn attestation_evaluate(
            &mut self,
            request: impl tonic::IntoRequest<super::AttestationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AttestationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/attestation.AttestationService/AttestationEvaluate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "attestation.AttestationService",
                        "AttestationEvaluate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_attestation_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/attestation.AttestationService/SetAttestationPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "attestation.AttestationService",
                        "SetAttestationPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_attestation_challenge(
            &mut self,
            request: impl tonic::IntoRequest<super::ChallengeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChallengeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/attestation.AttestationService/GetAttestationChallenge",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "attestation.AttestationService",
                        "GetAttestationChallenge",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod attestation_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AttestationServiceServer.
    #[async_trait]
    pub trait AttestationService: Send + Sync + 'static {
        async fn attestation_evaluate(
            &self,
            request: tonic::Request<super::AttestationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AttestationResponse>,
            tonic::Status,
        >;
        async fn set_attestation_policy(
            &self,
            request: tonic::Request<super::SetPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPolicyResponse>,
            tonic::Status,
        >;
        async fn get_attestation_challenge(
            &self,
            request: tonic::Request<super::ChallengeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChallengeResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AttestationServiceServer<T: AttestationService> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T: AttestationService> AttestationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AttestationServiceServer<T>
    where
        T: AttestationService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/attestation.AttestationService/AttestationEvaluate" => {
                    #[allow(non_camel_case_types)]
                    struct AttestationEvaluateSvc<T: AttestationService>(pub Arc<T>);
                    impl<
                        T: AttestationService,
                    > tonic::server::UnaryService<super::AttestationRequest>
                    for AttestationEvaluateSvc<T> {
                        type Response = super::AttestationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AttestationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AttestationService>::attestation_evaluate(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AttestationEvaluateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/attestation.AttestationService/SetAttestationPolicy" => {
                    #[allow(non_camel_case_types)]
                    struct SetAttestationPolicySvc<T: AttestationService>(pub Arc<T>);
                    impl<
                        T: AttestationService,
                    > tonic::server::UnaryService<super::SetPolicyRequest>
                    for SetAttestationPolicySvc<T> {
                        type Response = super::SetPolicyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetPolicyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AttestationService>::set_attestation_policy(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetAttestationPolicySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/attestation.AttestationService/GetAttestationChallenge" => {
                    #[allow(non_camel_case_types)]
                    struct GetAttestationChallengeSvc<T: AttestationService>(pub Arc<T>);
                    impl<
                        T: AttestationService,
                    > tonic::server::UnaryService<super::ChallengeRequest>
                    for GetAttestationChallengeSvc<T> {
                        type Response = super::ChallengeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChallengeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AttestationService>::get_attestation_challenge(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAttestationChallengeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", tonic::Code::Unimplemented as i32)
                                .header(
                                    http::header::CONTENT_TYPE,
                                    tonic::metadata::GRPC_CONTENT_TYPE,
                                )
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: AttestationService> Clone for AttestationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: AttestationService> tonic::server::NamedService
    for AttestationServiceServer<T> {
        const NAME: &'static str = "attestation.AttestationService";
    }
}
